export const SET_API_KEY = 'SET_API_KEY';
export const SET_AUTHORIZATION_HEADER = 'SET_AUTHORIZATION_HEADER';

export const REQUEST_REPOSITORIES = 'REQUEST_REPOSITORIES';
export const RECEIVED_REPOSITORIES = 'RECEIVED_REPOSITORIES';
export const SET_REPOSITORIES = 'SET_REPOSITORIES';

export const SET_SELECTED_REPOSITORY = 'SET_SELECTED_REPOSITORY';
export const SET_SELECTED_USER = 'SET_SELECTED_USER';
export const SET_FILTER_PARAM = 'SET_FILTER_PARAM';

export const REQUEST_ISSUES = 'REQUEST_ISSUES';
export const RECEIVED_ISSUES = 'RECEIVED_ISSUES';
export const SET_ISSUES = 'SET_ISSUES';
